#!/bin/bash

# Copyright (c) 2018 Jarosław Wierzbicki
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

ENTRY=${1%/}

if ! which pv &>/dev/null; then
    echo "Utility 'pv' is not available. Install 'pv' for progress indication."

    if [ -d "${ENTRY}" ]; then
        echo "archiving directory: ${ENTRY}"
        tar -cjf $(basename ${ENTRY}).tar.bz2 -C $(dirname ${ENTRY}) \
            $(basename ${ENTRY})
    elif [ -f "${ENTRY}" ]; then
        echo "compressing file ${ENTRY}"
        bzip2 -zc ${ENTRY} > $(basename ${ENTRY}).bz2
    else
        echo "error: invalid file/directory: ${ENTRY}"
        exit 1
    fi
else
    if [ -d "${ENTRY}" ]; then
        echo "archiving directory: ${ENTRY}"
        tar -cf - -C $(dirname ${ENTRY}) $(basename ${ENTRY}) -P | \
            pv -s $(du -sb ${ENTRY} | awk '{print $1}') | \
            bzip2 -zc > $(basename ${ENTRY}).tar.bz2
    elif [ -f "${ENTRY}" ]; then
        echo "compressing file ${ENTRY}"
        cat ${ENTRY} | pv -s $(du -sb ${ENTRY} | awk '{print $1}') | \
            bzip2 -zc - > $(basename ${ENTRY}).bz2
    else
        echo "error: invalid file/directory"
        exit 2
    fi
fi
